### ISSUE TITLE
Intellisense/autocomplete not working

### ISSUE THREAD

**Issue by mdewidt** [Gamadril/led-basic-vscode#1]
![vscode-ledbasic](https://user-images.githubusercontent.com/40343099/41543747-c52a564a-7317-11e8-845e-2ea20cacdd83.jpg)

Installed fresh VS Code.
Installed LED-Basic extension.
Can't get intellisense/autocomplete to work.
LED-Basic commands are all recognized …

What am I doing wrong ?

**Comment by Gamadril** [comment]
It seems that the LED Basic recognition fails because you have a new document and it's not saved yet with the .bas extension. I will check if the detection can be improved. As I can see on the screenshot you already set the document type manually to LED Basic.

**Comment by mdewidt** [comment]
You were absolutely right. After saving as "test.bas"no problems anymore.
Thanks for this very useful extension !
