### ISSUE TITLE
Can't select serial port

### ISSUE THREAD

**Issue by kv1dr** [Gamadril/led-basic-vscode#2]
I can't select serial port in VSCode. Menu for selecting serial port is just not visible in right bottom corner (while device selection is visible). I am able to find Select serial port if I press F1, but it doesn't do anything, and I got an error `Cannot read properties of null (reading 'list')`.

Full log:

> mainThreadExtensionService.ts:76 TypeError: Cannot read properties of null (reading 'list')
> 	at Function.list (D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\blp-serial\lib\bindings\win32.js:12:34)
> 	at Function.SerialPort.list (D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\blp-serial\lib\serialport.js:644:29)
> 	at D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\SerialPort.js:56:16
> 	at new Promise (<anonymous>)
> 	at Function.list (D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\SerialPort.js:55:16)
> 	at D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\PortSelector.js:62:37
> 	at new Promise (<anonymous>)
> 	at PortSelector.getPortList (D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\PortSelector.js:61:16)
> 	at D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\PortSelector.js:34:18
> 	at new Promise (<anonymous>)
> 	at PortSelector.showSelection (D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\PortSelector.js:32:16)
> 	at D:\Users\kv1dr\.vscode\extensions\gamadril.led-basic-2.0.4\build\extension.js:85:37
> 	at m._executeContributedCommand (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
> 	at m.$executeContributedCommand (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
> 	at i._doInvokeHandler (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
> 	at i._invokeHandler (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
> 	at i._receiveRequest (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
> 	at i._receiveOneMessage (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
> 	at d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
> 	at u.invoke (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
> 	at v.fire (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
> 	at d.fire (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
> 	at d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
> 	at u.invoke (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
> 	at v.fire (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
> 	at d.fire (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
> 	at o._receiveMessage (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
> 	at d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
> 	at u.invoke (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
> 	at v.fire (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
> 	at v.acceptChunk (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
> 	at d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
> 	at Socket.P (d:\Users\kv1dr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
> 	at Socket.emit (node:events:390:28)
> 	at addChunk (node:internal/streams/readable:315:12)
> 	at readableAddChunk (node:internal/streams/readable:289:9)
> 	at Socket.Readable.push (node:internal/streams/readable:228:10)
> 	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
> $onExtensionRuntimeError @ mainThreadExtensionService.ts:76

VSCode version: 1.66.2
OS: Windows 11
LED Basic extension version: 2.0.4

**Comment by Gamadril** [comment]
Thanks for the report. I will check it.

**Comment by Gamadril** [comment]
please try the new version 2.0.5

**Comment by kv1dr** [comment]
Unfortunately, I didn't have time to test this yet. I will try this when I have some spare time.
